### ISSUE TITLE
Document the math power command

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [general-language-syntax/GLS#367]
> _New to GLS for [#hacktoberfest](https://hacktoberfest.digitalocean.com/)? Welcome!_
> _Be sure to read the docs at [glslang.org](https://www.glslang.org) and play on [aka.ms/gls-demo](https://aka.ms/gls-demo) to familiarize yourself._

E.g. `Math.pow(2, 3)` gives 8.

Note: should also update `docs/math.md`.

**Comment by Oire** [comment]
@JoshuaKGoldberg, I'd like to try and take this.

**Comment by JoshuaKGoldberg** [comment]
Super!

**Comment by JoshuaKGoldberg** [comment]
As of #377, the command exists. It just needs to have a row added in `docs/math.md` now.

**Comment by Oire** [comment]
@JoshuaKGoldberg, I take this, of course. However I would ask for help about how to proceed: there are no docs about various math commands such as `floor` or `min`, there is just an example about how to call such native commands. that's why I didn't document it properly when working on #377, sorry about that.

**Comment by JoshuaKGoldberg** [comment]
Good point. There should probably be a second table in `docs/math.md` for these native commands. Could you add that as the documentation part of this issue? I'm thinking it should have the GLS syntax, C# equivalent, and Python equivalent.

Thoughts?

**Comment by Oire** [comment]
OK, I'll do it.
